services:
  db:
    image: postgres:13
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: unless-stopped

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.ci # Using CI Dockerfile for consistency
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile # Use the unified Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
