services:
  db:
    image: postgres:13
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend-builder:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./front:/app
    command: sh -c "npm install && npm run build"
