services:
  db:
    image: postgres:13
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile.dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./back/app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/testdb

  frontend:
    image: node:20-alpine
    command: sh -c "if [ ! -d 'node_modules' ]; then npm install; fi && npm run dev -- --host"
    volumes:
      - ./front:/app
    ports:
      - "5173:5173"
    working_dir: /app
    depends_on:
      - backend
