services:
  db:
    image: postgres:13
    volumes:
      - ./db_data:/var/lib/postgresql/data/
      - ./postgres_config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    command: postgres -c 'hba_file=/etc/postgresql/pg_hba.conf'
    network_mode: service:backend

  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile.dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
      - "5432:5432"
      - "5173:5173"
    working_dir: /app/back
    environment:
      - DATABASE_URL=postgresql://user:password@localhost/testdb

  frontend:
    image: node:20-alpine
    command: sh -c "if [ ! -d 'node_modules' ]; then npm install; fi && npm run dev -- --host"
    volumes:
      - .:/app
    working_dir: /app/front
    network_mode: service:backend
