# Use an official Microsoft dev container image with Python 3.13
FROM mcr.microsoft.com/devcontainers/python:3.13-bullseye

# Set work directory
WORKDIR /app

# Install poetry
RUN pip install poetry

# Copy poetry lock and pyproject files
COPY pyproject.toml poetry.lock README.md  ./

# Install dependencies
RUN poetry config virtualenvs.create false && poetry install --no-root --no-interaction --no-ansi

# Copy the rest of the application
COPY . .

# Command to run the application
CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
