name: Simple CI Pipeline

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test-all:
    runs-on: ubuntu-latest
    name: Test All Services
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: testdb
      DB_USER: user
      DB_PASSWORD: password
      DATABASE_URL: "postgresql://user:password@db:5432/testdb"
      ENVIRONMENT: ci
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Start and wait for services
      run: |
        docker compose -f docker-compose.ci.yml up -d --wait
    
    - name: Run Tests
      run: |
        docker compose -f docker-compose.ci.yml exec -T backend poetry run pytest -v
    
    - name: Cleanup
      if: always()
      run: |
        docker compose -f docker-compose.ci.yml logs --no-color
        docker compose -f docker-compose.ci.yml down
